version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    timezone: Asia/Tokyo
  open-pull-requests-limit: 30
  groups:
    rspec-dependencies:
      patterns:
        - "rspec"
        - "rspec-*"
        - "rspec_*"
    rubocop-dependencies:
      patterns:
        - "rubocop"
        - "rubocop-*"

