cache_path: "./cache.txt"
xml_url: "http://www.j-wave.co.jp/top/xml/now_on_air_song.xml"

bitly:
  user_name: ""
  api_key: ""

oauth:
  consumer_key: ""
  consumer_secret: ""
  token: ""
  secret: ""
